#TravisCI
language: android

before_install:
  - chmod +x gradlew

   licenses:
            - 'android-sdk-preview-license-52d11cd2'
            - 'android-sdk-license-.+'
            - 'google-gdk-license-.+'




