#TravisCI
language: android
android:
  components:
  # Uncomment the lines below if you want to
      # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - build-tools-26.0.2

   # The SDK version used to compile your project
    - android-26

   # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'






