#TravisCI
language: android
os: windows
install: true

android:
  components:
  # Uncomment the lines below if you want to
      # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - build-tools-26.0.2

    #- chmod +x gradlew

   # The SDK version used to compile your project
    - android-26


  licenses:
    - 'android-sdk-license-.+'











