#TravisCI Details
language: android
os: windows


android:
  components:
  # Uncomment the lines below if you want to
      # use the latest revision of Android SDK Tools
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3

    #- chmod +x gradlew

   # The SDK version used to compile your project
    - android-27



  licenses:
    - 'android-sdk-license-.+'

script:
   - gradle build connectedCheck









