#TravisCI
language: android
android:
  components:
    - build-tools-27.0.3
    - android-26.1.1

before_install:
  - chmod +x gradlew

 licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'






